// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAO7doe4HovjxCUsRebGdtoSPMS5HJ-Js',
    appId: '1:421301472557:android:a3f95785f5cfc1d9d1d7a4',
    messagingSenderId: '421301472557',
    projectId: 'test-youtube-api-374609',
    storageBucket: 'test-youtube-api-374609.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf6tTZD60qXzGYKujPFRLEUC7I41EdI0k',
    appId: '1:421301472557:ios:9d8e5271504d9c94d1d7a4',
    messagingSenderId: '421301472557',
    projectId: 'test-youtube-api-374609',
    storageBucket: 'test-youtube-api-374609.appspot.com',
    androidClientId: '421301472557-8e7dnt1kdh4msn6l91pfplsok1291shg.apps.googleusercontent.com',
    iosClientId: '421301472557-mjpmcjunpuve9jubth3bkchc9qk7nhvh.apps.googleusercontent.com',
    iosBundleId: 'com.example.testYoutubeDataApiV3',
  );
}
